### ISSUE TITLE
Github repository link is broken

### ISSUE THREAD

**Issue by dgarridouma** [FIWARE/tutorials.Big-Data-Spark#5]
The instructions mentions a Github tutorial that doesn't exist:

git clone https://github.com/ging/fiware-cosmos-orion-spark-connector-tutorial.git

Kind regards,
Daniel.

**Comment by jason-fox** [comment]
Link is incorrect - should be: https://github.com/ging/fiware-cosmos-orion-spark-connector-examples

**Comment by dgarridouma** [comment]
Not sure. I think is this: https://github.com/FIWARE/tutorials.Big-Data-Spark.git
